apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-ai-gateway-cert
  namespace: ai-gateway
spec:
  secretName: envoy-ai-gateway-tls
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
