apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: envoy-ai-gateway
  namespace: ai-gateway
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: {{ .Values.domain }}
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: envoy-ai-gateway-tls
    allowedRoutes:
      namespaces:
        from: Same
  - name: http
    hostname: {{ .Values.domain }}
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
