apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: ai-backend-service-{{ .Values.modelName }}
  namespace: ai-gateway
spec:
  schema:
    name: OpenAI
  backendRef:
    name: {{ .Values.modelName }}-backend
    kind: Backend
    group: gateway.envoyproxy.io
  timeouts:
    request: 300s
