apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.modelName }}-predictor-cert
spec:
  secretName: {{ .Values.modelName }}-predictor-tls
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
