apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ .Values.modelName }}-backend
  namespace: ai-gateway
spec:
  endpoints:
    - fqdn:
        hostname: {{ .Values.modelName }}-predictor.using-system-models.svc.cluster.local
        port: 80
