apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: envoy-gateway-ref-grant-{{ .Values.modelName }}
  namespace: using-system-models
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: ai-gateway
  to:
  - group: ""
    kind: Service
