apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-{{ .Values.modelName }}-route
  namespace: ai-gateway
spec:
  schema:
    name: OpenAI
  parentRefs:
  - name: envoy-ai-gateway
    namespace: ai-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  rules:
  - matches:
    - headers:
      - type: Exact
        name: x-ai-eg-model
        value: {{ .Values.modelName }}
    backendRefs:
    - name: ai-backend-service-{{ .Values.modelName }}
      weight: 100
  llmRequestCosts:
  - metadataKey: llm_input_token
    type: InputToken
  - metadataKey: llm_output_token
    type: OutputToken
  - metadataKey: llm_total_token
    type: TotalToken
